tambah fitur update agus
avinska/ch7-quiz pull request #4
Opened 2022-04-11 06:34 UTC by Agusmaul96

2022-04-11 06:48 UTC, Agusmaul96 commented
update

2022-04-14 08:52 UTC, avinska requested changes
overall sudah mantap mas, tinggal diperbaiki sedikit miss di controller & routernya yaa mas agus

2022-04-14 08:52 UTC, avinska commented on controller/index.js
> +        model: Stock,
ini cukup include: 'stock' ajaa mas

2022-04-14 08:52 UTC, avinska commented on controller/index.js
> +  });
ditambahin error handling yaa

2022-04-14 08:52 UTC, avinska commented on controller/index.js
> +  ).catch((error) => {
kalau pakai async await pakainya try and catch yaa mas

2022-04-14 08:52 UTC, avinska commented on controller/index.js
> +        uuid: req.body.uuid,
data uuid didapat dari query params mas

2022-04-14 08:52 UTC, avinska commented on router/index.js
> +router.post("/product/update", updateProduct);
path untuk edit both get & post ke "/edit/:uuid" yaa mas

2022-04-14 15:29 UTC, Agusmaul96 commented on controller/index.js
> +        uuid: req.body.uuid,
Udah di coba pake query Params gak jalan makanya pake req.body

2022-04-14 15:30 UTC, Agusmaul96 commented on controller/index.js
> +        model: Stock,
Sebernya Kya gitu udah bisa juga si

2022-04-14 15:47 UTC, avinska commented on controller/index.js
> +        uuid: req.body.uuid,
req.body itu untuk ambil value dari form mas, kalau req.params dari url. kita pakainya params mas

2022-04-14 17:48 UTC, avinska approved these changes

2022-04-14 17:49 UTC, avinska commented on controller/index.js
> +        model: Stock,
wah nice info, sipp kalo gitu mas

2022-04-15 02:51 UTC, closed without merging

2022-04-15 02:52 UTC, Agusmaul96 commented
Yang ini mau di tutup